apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remote
  template:
    metadata:
      labels:
        app: remote
    spec:
      containers:
      - name: remote
        image: final:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: remote-service
spec:
  selector:
    app: remote
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 5000
  type: LoadBalancer
