apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/saikiranreddy2710/final.git
    targetRevision: HEAD
    path: /manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: default 
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
